/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fizzbuzz;

import java.util.*;
import java.util.stream.Collectors;

public class App {
    public static void fizzbuzzNew() {
        /*
        If i MOD 3: "FIZZ"
        IF i mod 5: "BUZZ"
        If i MOD 3 AND i MOD 5: "FIZZBUZZ"
         */

        int cap = 300;
        StringBuilder sb = new StringBuilder();
        String current = "";

        for (int i = 0; i <= cap; i++) {
            if (isDivBy(i, 11)) {
                current += "BONG";
            } else {
                if (isDivBy(i, 3)) {
                    current += "FIZZ";
                }
                if (isDivBy(i, 5)) {
                    current += "BUZZ";
                }
                if (isDivBy(i, 7)) {
                    current += "BANG";
                }
            }

            if (current.isEmpty()) {
                sb.append(i);
            }

            sb.append(current);
            sb.append("\n");
            current = "";
        }

        System.out.println(sb);
    }


    private static boolean isDivBy(int left, int right) {
        return left % right == 0;
    }

    public static ArrayList<Integer> getDivisorsList(int num) {
        int squareRoot = (int) Math.sqrt(num);
        ArrayList<Integer> divisorList = new ArrayList<>();
        divisorList.add(1);

        for (int i = 2; i <= squareRoot; i++) {
            if (num % i == 0) {
                divisorList.add(i);
            }
        }

        return divisorList;
    }

    public static void main(String[] args) {
//        getDivisorsList(12);
        fizzbuzzNew();
    }
}
