/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fizzbuzz;

import java.util.Arrays;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.Map;
import java.util.stream.Collectors;

public class App {
    public static void fizzbuzz() {
        int cap = 100;
        StringBuilder sb = new StringBuilder();

        // Iterate through numbers 1 -> 100
        for (int i = 1; i <= cap; i++) {
            // if i is only divisible by 3 and not 5
            if (isDivBy(i, 3) && !isDivBy(i, 5)) {
                sb.append("FIZZ\n");
            }
            // if i is only divisible by 5 and not 3
            else if (!isDivBy(i, 3) && isDivBy(i, 5)) {
                sb.append("BUZZ\n");
            }
            // if i is divisible by both
            else if (isDivBy(i, 3)) {
                sb.append("FIZZ BUZZ\n");
            }
            else {
                sb.append(i);
                sb.append("\n");
            }
        }

        System.out.println(sb);
    }

    private static boolean isDivBy(int left, int right) {
        return left % right == 0;
    }

    public static void main(String[] args) {
        fizzbuzz();
    }
}
